### ISSUE TITLE
Credits of @odysseusmax

### ISSUE THREAD

**Issue by FayasNoushad** [nacbots/BroadcastBot#1]
Its not from @MrBotDeveloper, Its first published thus code in @odysseusmax's [Screenshot Bot](https://github.com/odysseusmax/animated-lamp)

**Comment by FayasNoushad** [comment]
I think @MrBotDeveloper is updated or modified that code

**Comment by MrBotDeveloper** [comment]
Updated sir 👍

**Comment by MrBotDeveloper** [comment]
@FayasNoushad You can close the issue now if all ok 👍

**Comment by FayasNoushad** [comment]
Aa
